FROM node:20

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer en mode développement avec hot reload
CMD ["npm", "run", "dev"] 