FROM node:20

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Installer nodemon pour le hot reload
RUN npm install -g nodemon

# Copier le code source
COPY . .

# Exposer le port 3001
EXPOSE 3001

# Commande pour démarrer en mode développement avec hot reload
CMD ["nodemon", "server.js"] 